/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calc2;

/**
 *
 * @author Ozy
 */
public class Limite002 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Limite002
     */
    public Limite002() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        xa = new javax.swing.JTextField();
        potb = new javax.swing.JTextField();
        OpB = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        xb = new javax.swing.JTextField();
        OpC = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        labelc = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        labela = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Calcular1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Xtende = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pota = new javax.swing.JTextField();
        xc = new javax.swing.JTextField();
        potc = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        xa2 = new javax.swing.JTextField();
        OpB2 = new javax.swing.JTextField();
        pota2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        xb2 = new javax.swing.JTextField();
        potb2 = new javax.swing.JTextField();
        OpC2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        xc2 = new javax.swing.JTextField();
        potc2 = new javax.swing.JTextField();
        labelc1 = new javax.swing.JLabel();
        labelb1 = new javax.swing.JLabel();
        labela1 = new javax.swing.JLabel();
        OpMenu2 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("CALCLID");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(204, 204, 255));
        TITULO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(102, 102, 102));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("CALC.LIM");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 690, -1));

        a.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 34, 33));

        xa.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa.setText("X");
        jPanel1.add(xa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 34, 33));

        potb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potbActionPerformed(evt);
            }
        });
        jPanel1.add(potb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 24, -1));

        OpB.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpBActionPerformed(evt);
            }
        });
        jPanel1.add(OpB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 25, -1));

        b.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 34, 33));

        xb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb.setText("X");
        jPanel1.add(xb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 34, 33));

        OpC.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpCActionPerformed(evt);
            }
        });
        jPanel1.add(OpC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 25, -1));

        c.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 34, 33));

        labelc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc.setText("c");
        labelc.setToolTipText("");
        jPanel1.add(labelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 22, 33));

        labelb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb.setText("b");
        jPanel1.add(labelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 22, 33));

        labela.setBackground(new java.awt.Color(204, 204, 255));
        labela.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela.setText("a");
        jPanel1.add(labela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 44, 33));

        Resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 303, 35));

        Calcular1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Calcular1.setText("Calcular");
        Calcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 90, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("X ->");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        Xtende.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(Xtende, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 34, 32));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 278, 416, 7));

        pota.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potaActionPerformed(evt);
            }
        });
        jPanel1.add(pota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 24, -1));

        xc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc.setText("X");
        xc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcActionPerformed(evt);
            }
        });
        jPanel1.add(xc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 34, 33));

        potc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potcActionPerformed(evt);
            }
        });
        jPanel1.add(potc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 24, -1));

        a2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 34, 33));

        xa2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa2.setText("X");
        jPanel1.add(xa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 34, 33));

        OpB2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpB2ActionPerformed(evt);
            }
        });
        jPanel1.add(OpB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 25, -1));

        pota2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pota2ActionPerformed(evt);
            }
        });
        jPanel1.add(pota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 24, -1));

        b2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 34, 33));

        xb2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb2.setText("X");
        jPanel1.add(xb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 34, 33));

        potb2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potb2ActionPerformed(evt);
            }
        });
        jPanel1.add(potb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 24, -1));

        OpC2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpC2ActionPerformed(evt);
            }
        });
        jPanel1.add(OpC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 25, -1));

        c2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 34, 33));

        xc2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc2.setText("X");
        xc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xc2ActionPerformed(evt);
            }
        });
        jPanel1.add(xc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 34, 33));

        potc2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potc2ActionPerformed(evt);
            }
        });
        jPanel1.add(potc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 24, -1));

        labelc1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc1.setText("c");
        labelc1.setToolTipText("");
        jPanel1.add(labelc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 22, 33));

        labelb1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb1.setText("b");
        jPanel1.add(labelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 22, 33));

        labela1.setBackground(new java.awt.Color(204, 204, 255));
        labela1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela1.setText("a");
        jPanel1.add(labela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 44, 33));

        OpMenu2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(OpMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 24, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void potbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potbActionPerformed

    private void OpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpBActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void OpCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpCActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void Calcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular1ActionPerformed
        // TODO add your handling code here:

        double aa = Double.parseDouble(a.getText());
        double bb = Double.parseDouble(b.getText());
        double cc = Double.parseDouble(c.getText());
        double potaa = Double.parseDouble(pota.getText());
        double potbb = Double.parseDouble(potb.getText());
        double potcc = Double.parseDouble(potc.getText());
        String OpBB = OpB.getText();
        String OpCC = OpC.getText();
        double x1 = Double.parseDouble(Xtende.getText());
        double resultA = aa*Math.pow(x1,potaa);
        double resultB = bb*Math.pow(x1,potbb);
        double resultC = cc*Math.pow(x1,potcc);
        double ResultAB;
        double ResultABC;
        if("+".equals(OpBB))
        { ResultAB = resultA + resultB;}
        else
        { ResultAB = resultA - resultB;}
        if("+".equals(OpCC))
        { ResultABC = ResultAB + resultC;}
        else
        { ResultABC = ResultAB - resultC;}
        Resultado.setText("Lim: " + ResultABC);

        double aa2 = Double.parseDouble(a2.getText());
        double bb2 = Double.parseDouble(b2.getText());
        double cc2 = Double.parseDouble(c2.getText());
        double potaa2 = Double.parseDouble(pota2.getText());
        double potbb2 = Double.parseDouble(potb2.getText());
        double potcc2 = Double.parseDouble(potc2.getText());
        String OpBB2 = OpB2.getText();
        String OpCC2 = OpC2.getText();
        double resultA2 = aa2*Math.pow(x1,potaa2);
        double resultB2 = bb2*Math.pow(x1,potbb2);
        double resultC2 = bb2*Math.pow(x1,potcc2);
        double ResultAB2;
        double ResultABC2;
        if("+".equals(OpBB2))
        { ResultAB2 = resultA2 + resultB2;}
        else
        { ResultAB2 = resultA2 - resultB2;}
        if("+".equals(OpCC2))
        { ResultABC2 = ResultAB2 + resultC2;}
        else
        { ResultABC2 = ResultAB2 - resultC2;}
        String OpMenu22 = OpMenu2.getText();

        double Resultado2;
        if("+".equals(OpMenu22))
        { Resultado2 = ResultABC + ResultABC2;}
        else
        { Resultado2 = ResultABC - ResultABC2;}

        Resultado.setText("Lim: " + Resultado2);

    }//GEN-LAST:event_Calcular1ActionPerformed

    private void potaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potaActionPerformed

    private void xcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcActionPerformed

    private void potcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potcActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void OpB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpB2ActionPerformed

    private void pota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pota2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void potb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potb2ActionPerformed

    private void OpC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpC2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void xc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xc2ActionPerformed

    private void potc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potc2ActionPerformed

    private void OpMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpMenu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular1;
    private javax.swing.JTextField OpB;
    private javax.swing.JTextField OpB2;
    private javax.swing.JTextField OpC;
    private javax.swing.JTextField OpC2;
    private javax.swing.JTextField OpMenu2;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextField Xtende;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labela1;
    private javax.swing.JLabel labelb;
    private javax.swing.JLabel labelb1;
    private javax.swing.JLabel labelc;
    private javax.swing.JLabel labelc1;
    private javax.swing.JTextField pota;
    private javax.swing.JTextField pota2;
    private javax.swing.JTextField potb;
    private javax.swing.JTextField potb2;
    private javax.swing.JTextField potc;
    private javax.swing.JTextField potc2;
    private javax.swing.JTextField xa;
    private javax.swing.JTextField xa2;
    private javax.swing.JTextField xb;
    private javax.swing.JTextField xb2;
    private javax.swing.JTextField xc;
    private javax.swing.JTextField xc2;
    // End of variables declaration//GEN-END:variables
}
