/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calc2;

/**
 *
 * @author Ozy
 */
public class Limite004 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Limite004
     */
    public Limite004() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        xa = new javax.swing.JTextField();
        potb = new javax.swing.JTextField();
        OpB = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        xb = new javax.swing.JTextField();
        OpC = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        labelc = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        labela = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Calcular1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Xtende = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pota = new javax.swing.JTextField();
        xc = new javax.swing.JTextField();
        potc = new javax.swing.JTextField();
        potc3 = new javax.swing.JTextField();
        xc3 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        labelc1 = new javax.swing.JLabel();
        potb3 = new javax.swing.JTextField();
        OpC3 = new javax.swing.JTextField();
        xb3 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        labelb1 = new javax.swing.JLabel();
        pota3 = new javax.swing.JTextField();
        labela1 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        xa3 = new javax.swing.JTextField();
        OpB3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        xa2 = new javax.swing.JTextField();
        labela6 = new javax.swing.JLabel();
        OpB2 = new javax.swing.JTextField();
        pota2 = new javax.swing.JTextField();
        labela7 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        xa4 = new javax.swing.JTextField();
        pota4 = new javax.swing.JTextField();
        OpB4 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        xb4 = new javax.swing.JTextField();
        OpC4 = new javax.swing.JTextField();
        xc4 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        potb4 = new javax.swing.JTextField();
        labelb6 = new javax.swing.JLabel();
        labelc6 = new javax.swing.JLabel();
        potc4 = new javax.swing.JTextField();
        xc2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        OpC2 = new javax.swing.JTextField();
        xb2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelb7 = new javax.swing.JLabel();
        potb2 = new javax.swing.JTextField();
        labelc7 = new javax.swing.JLabel();
        potc2 = new javax.swing.JTextField();
        OpMenu4 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("CALCLID");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(204, 204, 255));
        TITULO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(102, 102, 102));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("CALC.LIM");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 330, -1));

        a.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 34, 33));

        xa.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa.setText("X");
        jPanel1.add(xa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 34, 33));

        potb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potbActionPerformed(evt);
            }
        });
        jPanel1.add(potb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 24, -1));

        OpB.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpBActionPerformed(evt);
            }
        });
        jPanel1.add(OpB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 25, -1));

        b.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 34, 33));

        xb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb.setText("X");
        jPanel1.add(xb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 34, 33));

        OpC.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpCActionPerformed(evt);
            }
        });
        jPanel1.add(OpC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 25, -1));

        c.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 34, 33));

        labelc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc.setText("c");
        labelc.setToolTipText("");
        jPanel1.add(labelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 22, 33));

        labelb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb.setText("b");
        jPanel1.add(labelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 22, 33));

        labela.setBackground(new java.awt.Color(204, 204, 255));
        labela.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela.setText("a");
        jPanel1.add(labela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 44, 33));

        Resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 303, 35));

        Calcular1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Calcular1.setText("Calcular");
        Calcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("X ->");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 30, -1));

        Xtende.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(Xtende, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 34, 32));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 278, 416, 7));

        pota.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potaActionPerformed(evt);
            }
        });
        jPanel1.add(pota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 24, -1));

        xc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc.setText("X");
        xc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcActionPerformed(evt);
            }
        });
        jPanel1.add(xc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 34, 33));

        potc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potcActionPerformed(evt);
            }
        });
        jPanel1.add(potc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 24, -1));

        potc3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potc3ActionPerformed(evt);
            }
        });
        jPanel1.add(potc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 24, -1));

        xc3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc3.setText("X");
        xc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xc3ActionPerformed(evt);
            }
        });
        jPanel1.add(xc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 34, 33));

        c3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 34, 33));

        labelc1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc1.setText("c");
        labelc1.setToolTipText("");
        jPanel1.add(labelc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 22, 33));

        potb3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potb3ActionPerformed(evt);
            }
        });
        jPanel1.add(potb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 24, -1));

        OpC3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpC3ActionPerformed(evt);
            }
        });
        jPanel1.add(OpC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 25, -1));

        xb3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb3.setText("X");
        jPanel1.add(xb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 34, 33));

        b3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 34, 33));

        labelb1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb1.setText("b");
        jPanel1.add(labelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 22, 33));

        pota3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pota3ActionPerformed(evt);
            }
        });
        jPanel1.add(pota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 24, -1));

        labela1.setBackground(new java.awt.Color(204, 204, 255));
        labela1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela1.setText("a");
        jPanel1.add(labela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 44, 33));

        a3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 34, 33));

        xa3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa3.setText("X");
        jPanel1.add(xa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 34, 33));

        OpB3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpB3ActionPerformed(evt);
            }
        });
        jPanel1.add(OpB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 25, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("_______________");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 60));

        a2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 34, 33));

        xa2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa2.setText("X");
        jPanel1.add(xa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 34, 33));

        labela6.setBackground(new java.awt.Color(204, 204, 255));
        labela6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela6.setText("a");
        jPanel1.add(labela6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 44, 33));

        OpB2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpB2ActionPerformed(evt);
            }
        });
        jPanel1.add(OpB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 25, -1));

        pota2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pota2ActionPerformed(evt);
            }
        });
        jPanel1.add(pota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 24, -1));

        labela7.setBackground(new java.awt.Color(204, 204, 255));
        labela7.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela7.setText("a");
        jPanel1.add(labela7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 44, 33));

        a4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 34, 33));

        xa4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa4.setText("X");
        jPanel1.add(xa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 34, 33));

        pota4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pota4ActionPerformed(evt);
            }
        });
        jPanel1.add(pota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 24, -1));

        OpB4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpB4ActionPerformed(evt);
            }
        });
        jPanel1.add(OpB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 25, -1));

        b4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 34, 33));

        xb4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb4.setText("X");
        jPanel1.add(xb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 34, 33));

        OpC4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpC4ActionPerformed(evt);
            }
        });
        jPanel1.add(OpC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 25, -1));

        xc4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc4.setText("X");
        xc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xc4ActionPerformed(evt);
            }
        });
        jPanel1.add(xc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 34, 33));

        c4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 34, 33));

        potb4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potb4ActionPerformed(evt);
            }
        });
        jPanel1.add(potb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 24, -1));

        labelb6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb6.setText("b");
        jPanel1.add(labelb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 22, 33));

        labelc6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc6.setText("c");
        labelc6.setToolTipText("");
        jPanel1.add(labelc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 22, 33));

        potc4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potc4ActionPerformed(evt);
            }
        });
        jPanel1.add(potc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 24, -1));

        xc2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc2.setText("X");
        xc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xc2ActionPerformed(evt);
            }
        });
        jPanel1.add(xc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 34, 33));

        c2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 34, 33));

        OpC2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpC2ActionPerformed(evt);
            }
        });
        jPanel1.add(OpC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 25, -1));

        xb2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb2.setText("X");
        jPanel1.add(xb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 34, 33));

        b2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 34, 33));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("_______________");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 310, 60));

        labelb7.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb7.setText("b");
        jPanel1.add(labelb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 22, 33));

        potb2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potb2ActionPerformed(evt);
            }
        });
        jPanel1.add(potb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 24, -1));

        labelc7.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc7.setText("c");
        labelc7.setToolTipText("");
        jPanel1.add(labelc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 22, 33));

        potc2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potc2ActionPerformed(evt);
            }
        });
        jPanel1.add(potc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 24, -1));

        OpMenu4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMenu4ActionPerformed(evt);
            }
        });
        jPanel1.add(OpMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 24, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void potbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potbActionPerformed

    private void OpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpBActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void OpCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpCActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void Calcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular1ActionPerformed
        // TODO add your handling code here:

        double aa = Double.parseDouble(a.getText());
        double bb = Double.parseDouble(b.getText());
        double cc = Double.parseDouble(c.getText());
        double potaa = Double.parseDouble(pota.getText());
        double potbb = Double.parseDouble(potb.getText());
        double potcc = Double.parseDouble(potc.getText());
        String OpBB = OpB.getText();
        String OpCC = OpC.getText();
        double x1 = Double.parseDouble(Xtende.getText());
        double resultA = aa*Math.pow(x1,potaa);
        double resultB = bb*Math.pow(x1,potbb);
        double resultC = cc*Math.pow(x1,potcc);
        double ResultAB;
        double ResultABC;
        if("+".equals(OpBB))
        { ResultAB = resultA + resultB;}
        else
        { ResultAB = resultA - resultB;}
        if("+".equals(OpCC))
        { ResultABC = ResultAB + resultC;}
        else
        { ResultABC = ResultAB - resultC;}

        double aa3 = Double.parseDouble(a3.getText());
        double bb3 = Double.parseDouble(b3.getText());
        double cc3 = Double.parseDouble(c3.getText());
        double potaa3 = Double.parseDouble(pota3.getText());
        double potbb3 = Double.parseDouble(potb3.getText());
        double potcc3 = Double.parseDouble(potc3.getText());
        String OpBB3 = OpB3.getText();
        String OpCC3 = OpC3.getText();
        double resultA3 = aa3*Math.pow(x1,potaa3);
        double resultB3 = bb3*Math.pow(x1,potbb3);
        double resultC3 = cc3*Math.pow(x1,potcc3);
        double ResultAB3;
        double ResultABC3;
        if("+".equals(OpBB3))
        { ResultAB3 = resultA3 + resultB;}
        else
        { ResultAB3 = resultA3 - resultB3;}
        if("+".equals(OpCC))
        { ResultABC3 = ResultAB3 + resultC3;}
        else
        { ResultABC3 = ResultAB3 - resultC3;}

        double Resultado3 = ResultABC/ResultABC3;

        double aa2 = Double.parseDouble(a2.getText());
        double bb2 = Double.parseDouble(b2.getText());
        double cc2 = Double.parseDouble(c2.getText());
        double potaa2 = Double.parseDouble(pota2.getText());
        double potbb2 = Double.parseDouble(potb2.getText());
        double potcc2 = Double.parseDouble(potc2.getText());
        String OpBB2 = OpB2.getText();
        String OpCC2 = OpC2.getText();
        double resultA2 = aa2*Math.pow(x1,potaa2);
        double resultB2 = bb2*Math.pow(x1,potbb2);
        double resultC2 = cc2*Math.pow(x1,potcc2);
        double ResultAB2;
        double ResultABC2;
        if("+".equals(OpBB2))
        { ResultAB2 = resultA2 + resultB2;}
        else
        { ResultAB2 = resultA2 - resultB2;}
        if("+".equals(OpCC2))
        { ResultABC2 = ResultAB2 + resultC2;}
        else
        { ResultABC2 = ResultAB2 - resultC2;}

        double aa4 = Double.parseDouble(a4.getText());
        double bb4 = Double.parseDouble(b4.getText());
        double cc4 = Double.parseDouble(c4.getText());
        double potaa4 = Double.parseDouble(pota4.getText());
        double potbb4 = Double.parseDouble(potb4.getText());
        double potcc4 = Double.parseDouble(potc4.getText());
        String OpBB4 = OpB4.getText();
        String OpCC4 = OpC4.getText();
        double resultA4 = aa4*Math.pow(x1,potaa4);
        double resultB4 = bb4*Math.pow(x1,potbb4);
        double resultC4 = cc4*Math.pow(x1,potcc4);
        double ResultAB4;
        double ResultABC4;
        if("+".equals(OpBB4))
        { ResultAB4 = resultA4 + resultB4;}
        else
        { ResultAB4 = resultA4 - resultB4;}
        if("+".equals(OpCC4))
        { ResultABC4 = ResultAB4 + resultC4;}
        else
        { ResultABC4 = ResultAB4 - resultC4;}

        double Resultado4 = ResultABC2/ResultABC4;

        String OpMenu44 = OpMenu4.getText();
        double Resultado5;

        if("+".equals(OpMenu44))
        { Resultado5 = Resultado3 + Resultado4;}
        else
        { Resultado5 = Resultado3 - Resultado4;}

        Resultado.setText("Lim: " + Resultado5);

    }//GEN-LAST:event_Calcular1ActionPerformed

    private void potaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potaActionPerformed

    private void xcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcActionPerformed

    private void potcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potcActionPerformed

    private void potc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potc3ActionPerformed

    private void xc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xc3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void potb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potb3ActionPerformed

    private void OpC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpC3ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void pota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pota3ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void OpB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpB3ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void OpB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpB2ActionPerformed

    private void pota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pota2ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void pota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pota4ActionPerformed

    private void OpB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpB4ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void OpC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpC4ActionPerformed

    private void xc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xc4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void potb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potb4ActionPerformed

    private void potc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potc4ActionPerformed

    private void xc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xc2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void OpC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpC2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void potb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potb2ActionPerformed

    private void potc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potc2ActionPerformed

    private void OpMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpMenu4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular1;
    private javax.swing.JTextField OpB;
    private javax.swing.JTextField OpB2;
    private javax.swing.JTextField OpB3;
    private javax.swing.JTextField OpB4;
    private javax.swing.JTextField OpC;
    private javax.swing.JTextField OpC2;
    private javax.swing.JTextField OpC3;
    private javax.swing.JTextField OpC4;
    private javax.swing.JTextField OpMenu4;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextField Xtende;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labela1;
    private javax.swing.JLabel labela6;
    private javax.swing.JLabel labela7;
    private javax.swing.JLabel labelb;
    private javax.swing.JLabel labelb1;
    private javax.swing.JLabel labelb6;
    private javax.swing.JLabel labelb7;
    private javax.swing.JLabel labelc;
    private javax.swing.JLabel labelc1;
    private javax.swing.JLabel labelc6;
    private javax.swing.JLabel labelc7;
    private javax.swing.JTextField pota;
    private javax.swing.JTextField pota2;
    private javax.swing.JTextField pota3;
    private javax.swing.JTextField pota4;
    private javax.swing.JTextField potb;
    private javax.swing.JTextField potb2;
    private javax.swing.JTextField potb3;
    private javax.swing.JTextField potb4;
    private javax.swing.JTextField potc;
    private javax.swing.JTextField potc2;
    private javax.swing.JTextField potc3;
    private javax.swing.JTextField potc4;
    private javax.swing.JTextField xa;
    private javax.swing.JTextField xa2;
    private javax.swing.JTextField xa3;
    private javax.swing.JTextField xa4;
    private javax.swing.JTextField xb;
    private javax.swing.JTextField xb2;
    private javax.swing.JTextField xb3;
    private javax.swing.JTextField xb4;
    private javax.swing.JTextField xc;
    private javax.swing.JTextField xc2;
    private javax.swing.JTextField xc3;
    private javax.swing.JTextField xc4;
    // End of variables declaration//GEN-END:variables
}
