/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calc2;

/**
 *
 * @author Ozy
 */
public class Limite003 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Limite003
     */
    public Limite003() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        xa = new javax.swing.JTextField();
        potb = new javax.swing.JTextField();
        OpB = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        xb = new javax.swing.JTextField();
        OpC = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        labelc = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        labela = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Calcular1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Xtende = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pota = new javax.swing.JTextField();
        xc = new javax.swing.JTextField();
        potc = new javax.swing.JTextField();
        potc3 = new javax.swing.JTextField();
        xc3 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        labelc1 = new javax.swing.JLabel();
        potb3 = new javax.swing.JTextField();
        OpC3 = new javax.swing.JTextField();
        xb3 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        labelb1 = new javax.swing.JLabel();
        pota3 = new javax.swing.JTextField();
        labela1 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        xa3 = new javax.swing.JTextField();
        OpB3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("CALCLID");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(204, 204, 255));
        TITULO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(102, 102, 102));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("CALC.LIM");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 330, -1));

        a.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 34, 33));

        xa.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa.setText("X");
        jPanel1.add(xa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 34, 33));

        potb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potbActionPerformed(evt);
            }
        });
        jPanel1.add(potb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 24, -1));

        OpB.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpBActionPerformed(evt);
            }
        });
        jPanel1.add(OpB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 25, -1));

        b.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 34, 33));

        xb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb.setText("X");
        jPanel1.add(xb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 34, 33));

        OpC.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpCActionPerformed(evt);
            }
        });
        jPanel1.add(OpC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 25, -1));

        c.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 34, 33));

        labelc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc.setText("c");
        labelc.setToolTipText("");
        jPanel1.add(labelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 22, 33));

        labelb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb.setText("b");
        jPanel1.add(labelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 22, 33));

        labela.setBackground(new java.awt.Color(204, 204, 255));
        labela.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela.setText("a");
        jPanel1.add(labela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 44, 33));

        Resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 303, 35));

        Calcular1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Calcular1.setText("Calcular");
        Calcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("X ->");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        Xtende.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(Xtende, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 34, 32));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 278, 416, 7));

        pota.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potaActionPerformed(evt);
            }
        });
        jPanel1.add(pota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 24, -1));

        xc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc.setText("X");
        xc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcActionPerformed(evt);
            }
        });
        jPanel1.add(xc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 34, 33));

        potc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potcActionPerformed(evt);
            }
        });
        jPanel1.add(potc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 24, -1));

        potc3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potc3ActionPerformed(evt);
            }
        });
        jPanel1.add(potc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 24, -1));

        xc3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xc3.setText("X");
        xc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xc3ActionPerformed(evt);
            }
        });
        jPanel1.add(xc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 34, 33));

        c3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 34, 33));

        labelc1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc1.setText("c");
        labelc1.setToolTipText("");
        jPanel1.add(labelc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 22, 33));

        potb3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        potb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potb3ActionPerformed(evt);
            }
        });
        jPanel1.add(potb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 24, -1));

        OpC3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpC3ActionPerformed(evt);
            }
        });
        jPanel1.add(OpC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 25, -1));

        xb3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xb3.setText("X");
        jPanel1.add(xb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 34, 33));

        b3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 34, 33));

        labelb1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb1.setText("b");
        jPanel1.add(labelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 22, 33));

        pota3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pota3ActionPerformed(evt);
            }
        });
        jPanel1.add(pota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 24, -1));

        labela1.setBackground(new java.awt.Color(204, 204, 255));
        labela1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela1.setText("a");
        jPanel1.add(labela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 44, 33));

        a3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 34, 33));

        xa3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        xa3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        xa3.setText("X");
        jPanel1.add(xa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 34, 33));

        OpB3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        OpB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpB3ActionPerformed(evt);
            }
        });
        jPanel1.add(OpB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 25, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("_______________");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void potbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potbActionPerformed

    private void OpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpBActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void OpCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpCActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void Calcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular1ActionPerformed
        // TODO add your handling code here:

        double aa = Double.parseDouble(a.getText());
        double bb = Double.parseDouble(b.getText());
        double cc = Double.parseDouble(c.getText());
        double potaa = Double.parseDouble(pota.getText());
        double potbb = Double.parseDouble(potb.getText());
        double potcc = Double.parseDouble(potc.getText());
        String OpBB = OpB.getText();
        String OpCC = OpC.getText();
        double x1 = Double.parseDouble(Xtende.getText());
        double resultA = aa*Math.pow(x1,potaa);
        double resultB = bb*Math.pow(x1,potbb);
        double resultC = cc*Math.pow(x1,potcc);
        double ResultAB;
        double ResultABC;
        if("+".equals(OpBB))
        { ResultAB = resultA + resultB;}
        else
        { ResultAB = resultA - resultB;}
        if("+".equals(OpCC))
        { ResultABC = ResultAB + resultC;}
        else
        { ResultABC = ResultAB - resultC;}

        double aa3 = Double.parseDouble(a3.getText());
        double bb3 = Double.parseDouble(b3.getText());
        double cc3 = Double.parseDouble(c3.getText());
        double potaa3 = Double.parseDouble(pota3.getText());
        double potbb3 = Double.parseDouble(potb3.getText());
        double potcc3 = Double.parseDouble(potc3.getText());
        String OpBB3 = OpB3.getText();
        String OpCC3 = OpC3.getText();
        double resultA3 = aa3*Math.pow(x1,potaa3);
        double resultB3 = bb3*Math.pow(x1,potbb3);
        double resultC3 = cc3*Math.pow(x1,potcc3);
        double ResultAB3;
        double ResultABC3;
        if("+".equals(OpBB3))
        { ResultAB3 = resultA3 + resultB;}
        else
        { ResultAB3 = resultA3 - resultB3;}
        if("+".equals(OpCC))
        { ResultABC3 = ResultAB3 + resultC3;}
        else
        { ResultABC3 = ResultAB3 - resultC3;}

        double Resultado3 = ResultABC/ResultABC3;
        Resultado.setText("Lim: " + Resultado3);
    }//GEN-LAST:event_Calcular1ActionPerformed

    private void potaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potaActionPerformed

    private void xcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcActionPerformed

    private void potcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potcActionPerformed

    private void potc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potc3ActionPerformed

    private void xc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xc3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void potb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potb3ActionPerformed

    private void OpC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpC3ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void pota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pota3ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void OpB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpB3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular1;
    private javax.swing.JTextField OpB;
    private javax.swing.JTextField OpB3;
    private javax.swing.JTextField OpC;
    private javax.swing.JTextField OpC3;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextField Xtende;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labela1;
    private javax.swing.JLabel labelb;
    private javax.swing.JLabel labelb1;
    private javax.swing.JLabel labelc;
    private javax.swing.JLabel labelc1;
    private javax.swing.JTextField pota;
    private javax.swing.JTextField pota3;
    private javax.swing.JTextField potb;
    private javax.swing.JTextField potb3;
    private javax.swing.JTextField potc;
    private javax.swing.JTextField potc3;
    private javax.swing.JTextField xa;
    private javax.swing.JTextField xa3;
    private javax.swing.JTextField xb;
    private javax.swing.JTextField xb3;
    private javax.swing.JTextField xc;
    private javax.swing.JTextField xc3;
    // End of variables declaration//GEN-END:variables
}
