/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

/**
 *
 * @author ALUNO
 */
public class ozyf extends javax.swing.JFrame {

    /**
     * Creates new form ozyf
     */
    public ozyf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        ax = new javax.swing.JTextField();
        pot = new javax.swing.JTextField();
        Sinal1 = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        bx = new javax.swing.JTextField();
        Sinal2 = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        labelc = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        labela = new javax.swing.JLabel();
        MontarEq = new javax.swing.JButton();
        Equacao = new javax.swing.JTextField();
        SelLim1 = new javax.swing.JCheckBox();
        SelDer1 = new javax.swing.JCheckBox();
        SelInt1 = new javax.swing.JCheckBox();
        Calcular1 = new javax.swing.JButton();
        ResLim = new javax.swing.JTextField();
        ResDer = new javax.swing.JTextField();
        ResInt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Xtende = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        S1 = new javax.swing.JTextField();
        S2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("CALCLID");

        TITULO.setBackground(new java.awt.Color(204, 204, 255));
        TITULO.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(102, 102, 102));
        TITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO.setText("CALC.LID");

        a.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        ax.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ax.setText("X");

        pot.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potActionPerformed(evt);
            }
        });

        Sinal1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Sinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sinal1ActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        bx.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        bx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bx.setText("X");

        Sinal2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Sinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sinal2ActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        labelc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelc.setText("c");
        labelc.setToolTipText("");

        labelb.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelb.setText("b");

        labela.setBackground(new java.awt.Color(204, 204, 255));
        labela.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        labela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labela.setText("a");

        MontarEq.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        MontarEq.setText("Montar Equação");
        MontarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontarEqActionPerformed(evt);
            }
        });

        Equacao.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Equacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquacaoActionPerformed(evt);
            }
        });

        SelLim1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        SelLim1.setText("Limite");
        SelLim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelLim1ActionPerformed(evt);
            }
        });

        SelDer1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        SelDer1.setText("Derivada");
        SelDer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelDer1ActionPerformed(evt);
            }
        });

        SelInt1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        SelInt1.setText("Integral");
        SelInt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelInt1ActionPerformed(evt);
            }
        });

        Calcular1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Calcular1.setText("Calcular");
        Calcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular1ActionPerformed(evt);
            }
        });

        ResLim.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ResLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResLimActionPerformed(evt);
            }
        });

        ResDer.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ResDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResDerActionPerformed(evt);
            }
        });

        ResInt.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ResInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResIntActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("X ->");

        Xtende.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("S");

        S1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        S2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Equacao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(SelLim1)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SelDer1)
                                    .addComponent(Calcular1))
                                .addGap(18, 18, 18)
                                .addComponent(SelInt1)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ResInt)
                            .addComponent(ResDer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResLim, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(labela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Sinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Xtende, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(MontarEq)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITULO)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(pot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labela, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Xtende, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MontarEq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Equacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelLim1)
                    .addComponent(SelDer1)
                    .addComponent(SelInt1))
                .addGap(18, 18, 18)
                .addComponent(Calcular1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResLim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResDer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResInt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        a.getText();
    }//GEN-LAST:event_aActionPerformed

    private void potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potActionPerformed
        // TODO add your handling code here:
        pot.getText();
    }//GEN-LAST:event_potActionPerformed

    private void Sinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sinal1ActionPerformed
        // TODO add your handling code here:
        Sinal1.getText();
    }//GEN-LAST:event_Sinal1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        b.getText();
    }//GEN-LAST:event_bActionPerformed

    private void Sinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sinal2ActionPerformed
        // TODO add your handling code here:
        Sinal2.getText();
    }//GEN-LAST:event_Sinal2ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        c.getText();
    }//GEN-LAST:event_cActionPerformed

    private void MontarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontarEqActionPerformed

        String a1 = a.getText();
        String b1 = b.getText();
        String c1 = c.getText();
        String pot1 = pot.getText();
        String Sinal1b = Sinal1.getText();
        String Sinal2b = Sinal2.getText();
        Equacao.setText(a1+"x"+"^"+pot1+ Sinal1b + b1 +"x" + Sinal2b + c1);
    }//GEN-LAST:event_MontarEqActionPerformed

    private void EquacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquacaoActionPerformed

    private void SelLim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelLim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelLim1ActionPerformed

    private void SelDer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelDer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelDer1ActionPerformed

    private void SelInt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelInt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelInt1ActionPerformed

    private void Calcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular1ActionPerformed
        // TODO add your handling code here:
        { if(SelLim1.isSelected())
            {
                String a1 = a.getText();
                String b1 = b.getText();
                String c1 = c.getText();
                String pot1 = pot.getText();
                String Sinal1b = Sinal1.getText();
                String Sinal2b = Sinal2.getText();
                String x1 = Xtende.getText();
                ResLim.setText("Lim: " + a1 +"*"+x1 +"^" +pot1 + Sinal1b +b1 +"*"+x1 + ")"+ Sinal2b +c1);

            }
            else
            ResLim.setText(" ");
        }
        { if(SelDer1.isSelected())
            {
                String a1 = a.getText();
                String b1 = b.getText();
                String c1 = c.getText();
                String pot1 = pot.getText();
                double pot2 = Double.parseDouble(pot1);
                String Sinal1b = Sinal1.getText();
                String Sinal2b = Sinal2.getText();
                String x1 = Xtende.getText();
                ResDer.setText("f(x)': " + pot1 + "*" + a1 +"*"+x1 +"^" +(pot2-1) + Sinal1b +b1);

            }
            else
            ResDer.setText(" ");
        }
        {if(SelInt1.isSelected())
            {
                String a1 = a.getText();
                String b1 = b.getText();
                String c1 = c.getText();
                String pot1 = pot.getText();
                double pot2 = Double.parseDouble(pot1);
                String Sinal1b = Sinal1.getText();
                String Sinal2b = Sinal2.getText();
                String sa = S1.getText();
                double sa1 = Double.parseDouble(sa);
                String sb = S2.getText();
                double sb1 = Double.parseDouble(sb);
                ResInt.setText("S: [(" + a1 +"*"+sa1 +"^" + (pot2+1) + ")/" + (pot2+1) + Sinal1b +"("+b1 +"*"+sa1 + "^2" + ")/" + (2) + Sinal2b +"(" +c1 + "*" + sa1 +")/] - [(" + a1 +"*"+sb1 +"^" + (pot2+1) + ")/" + (pot2+1) + Sinal1b +"("+b1 +"*"+sb1 + "^2" + ")/" + (2) + Sinal2b +"(" +c1 + "*" + sb1 +")/]");
            }
            else
            ResInt.setText(" ");
        }

    }//GEN-LAST:event_Calcular1ActionPerformed

    private void ResLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResLimActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ResLimActionPerformed

    private void ResDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResDerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ResDerActionPerformed

    private void ResIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResIntActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ResIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ozyf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ozyf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ozyf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ozyf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ozyf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular1;
    private javax.swing.JTextField Equacao;
    private javax.swing.JButton MontarEq;
    private javax.swing.JTextField ResDer;
    private javax.swing.JTextField ResInt;
    private javax.swing.JTextField ResLim;
    private javax.swing.JTextField S1;
    private javax.swing.JTextField S2;
    private javax.swing.JCheckBox SelDer1;
    private javax.swing.JCheckBox SelInt1;
    private javax.swing.JCheckBox SelLim1;
    private javax.swing.JTextField Sinal1;
    private javax.swing.JTextField Sinal2;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextField Xtende;
    private javax.swing.JTextField a;
    private javax.swing.JTextField ax;
    private javax.swing.JTextField b;
    private javax.swing.JTextField bx;
    private javax.swing.JTextField c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labelb;
    private javax.swing.JLabel labelc;
    private javax.swing.JTextField pot;
    // End of variables declaration//GEN-END:variables
}
